### ISSUE TITLE
Items jamming in queue

### ISSUE THREAD

**Issue by ChinaShopBully** [appuns/DSPReplicatorPlus#1]
This is a fantastic QoL mod. I love it!

However, I am frequently finding that my replicator queue has stalled because a single item is not replicating. I have to remove that item from the queue to get it moving again. I'm not certain how to replicate it yet, but it happens often enough that it is problematic on high diff settings with a lot of manual crafting.

**Comment by danieldonaldson** [comment]
Have the same issue as above

**Comment by appuns** [comment]
I'm sorry to be late. I think it has probably been resolved.

**Comment by BrutalRIP** [comment]
@appuns i think this is an issue still/again its happening to me anyway
